version: '3.1'

services:
  zeithub:
    image: m0gd0ck/zeithub:latest
    container_name: zeithub
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_NAME: zeithub
      DB_PASSWD: zeithub
      JWT_SECRET: yoursecretaintsecret
      NODE_ENV: production
      PORT: 80
    ports:
      - 80:80
  db:
    image: mysql:8
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: zeithub
      MYSQL_USER: zeithub
      MYSQL_PASSWORD: zeithub
      MYSQL_DATABASE: zeithub
    volumes:
      - ./docker/mysql:/var/lib/mysql
    expose:
      - '3306'
