version: '3.1'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: zeithub
      MYSQL_USER: zeithub
      MYSQL_PASSWORD: zeithub
      MYSQL_DATABASE: zeithub
    volumes:
      - ./docker/mysql:/var/lib/mysql
    ports:
      - '3306:3306'
    expose:
      - '3306'
